keys:
  mongodb:
    connectionString: mongodb://admin:amitava@ds029051.mongolab.com:29051/funnel
  redis:
    session:
      server: localhost
      port: 6379
      db: 0
  sessions:
    secret: TEd7RNcGnDsCqDyGWRPM3wahwXapjytS2Uod7st1
    key: 4ofcob7vut
    ttl: 86400000
    cookie:
      domain: .employd.io
      maxAge: 86400000
  mandrill:
    secret: xOzSbagjpBd4urFTHJrcQQ
urls:
      ui:
        host: employd.io
        port: 3000
        protocol: http
storage:
  path: /Users/amitava/funnel/data
server:
  host: employd.io
  port: 3000
